@baseUrl = http://localhost:3001
@contentType = application/json
@room = 1
@Name = John Doe
@Age = 25
@Address = 123 Main St
@City = New York
@zipCode = 10001
@status = married

### post message
POST {{baseUrl}}/message/{{room}}
content-type: {{contentType}}

{
    "name": "{{Name}}",
    "age": "{{Age}}",
    "address": "{{Address}}",
    "city": "{{City}}",
    "zipCode": "{{zipCode}}",
    "status": "{{status}}"
}

### get all messages
GET {{baseUrl}}/history/{{room}}
content-type: {{contentType}}